from motor.motor_asyncio import AsyncIOMotorDatabase
from pymongo import ASCENDING


async def create_indexes(db: AsyncIOMotorDatabase) -> None:
    await db.users.create_index([("email", ASCENDING)], unique=True)
    await db.user_profiles.create_index([("user_id", ASCENDING)], unique=True)
    await db.career_paths.create_index([("slug", ASCENDING)], unique=True)
    await db.career_paths.create_index([("title", ASCENDING)])
    await db.career_paths.create_index([("is_active", ASCENDING)])
    await db.career_assessments.create_index([("user_id", ASCENDING)])
    await db.career_assessments.create_index([("created_at", ASCENDING)])
    await db.career_matches.create_index([("user_id", ASCENDING)])
    await db.career_matches.create_index([("assessment_id", ASCENDING)])
    await db.career_matches.create_index([("best_match_career_id", ASCENDING)])
    await db.career_matches.create_index([("selected_career_id", ASCENDING)])
    await db.ml_career_predictions.create_index([("user_id", ASCENDING)])
    await db.ml_career_predictions.create_index([("assessment_id", ASCENDING)])
    await db.ml_career_predictions.create_index([("created_at", ASCENDING)])
    await db.ml_career_predictions.create_index([("final_recommended_career", ASCENDING)])
    await db.courses.create_index([("title", ASCENDING)])
    await db.courses.create_index([("difficulty", ASCENDING)])
    await db.courses.create_index([("provider", ASCENDING)])
    await db.courses.create_index([("course_type", ASCENDING)])
    await db.courses.create_index([("related_careers", ASCENDING)])
    await db.courses.create_index([("related_skills", ASCENDING)])
    await db.courses.create_index([("is_active", ASCENDING)])
    await db.courses.create_index([("title", ASCENDING), ("provider", ASCENDING)], unique=True)
    await db.course_recommendations.create_index([("user_id", ASCENDING)])
    await db.course_recommendations.create_index([("career_path_id", ASCENDING)])
    await db.course_recommendations.create_index([("assessment_id", ASCENDING)])
    await db.course_recommendations.create_index([("created_at", ASCENDING)])
    await db.saved_courses.create_index([("user_id", ASCENDING)])
    await db.saved_courses.create_index([("course_id", ASCENDING)])
    await db.saved_courses.create_index([("user_id", ASCENDING), ("course_id", ASCENDING)], unique=True)
    await db.adaptive_learning_paths.create_index([("user_id", ASCENDING)])
    await db.adaptive_learning_paths.create_index([("career_path_id", ASCENDING)])
    await db.adaptive_learning_paths.create_index([("assessment_id", ASCENDING)])
    await db.adaptive_learning_paths.create_index([("status", ASCENDING)])
    await db.adaptive_learning_paths.create_index([("user_id", ASCENDING), ("career_path_id", ASCENDING)])
    await db.learning_path_updates.create_index([("user_id", ASCENDING)])
    await db.learning_path_updates.create_index([("learning_path_id", ASCENDING)])
    await db.learning_path_updates.create_index([("created_at", ASCENDING)])
    await db.user_course_progress.create_index([("user_id", ASCENDING)])
    await db.user_course_progress.create_index([("course_id", ASCENDING)])
    await db.user_course_progress.create_index([("career_path_id", ASCENDING)])
    await db.user_course_progress.create_index([("learning_path_id", ASCENDING)])
    await db.user_course_progress.create_index([("phase_id", ASCENDING)])
    await db.user_course_progress.create_index([("status", ASCENDING)])
    await db.user_course_progress.create_index([("user_id", ASCENDING), ("course_id", ASCENDING)], unique=True)
    await db.user_skill_progress.create_index([("user_id", ASCENDING)])
    await db.user_skill_progress.create_index([("skill_name", ASCENDING)])
    await db.user_skill_progress.create_index([("status", ASCENDING)])
    await db.user_skill_progress.create_index([("related_career_path_id", ASCENDING)])
    await db.user_skill_progress.create_index([("user_id", ASCENDING), ("skill_name", ASCENDING)], unique=True)
    await db.progress_logs.create_index([("user_id", ASCENDING)])
    await db.progress_logs.create_index([("action_type", ASCENDING)])
    await db.progress_logs.create_index([("created_at", ASCENDING)])
    await db.study_activity_logs.create_index([("user_id", ASCENDING)])
    await db.study_activity_logs.create_index([("date", ASCENDING)])
    await db.study_activity_logs.create_index([("user_id", ASCENDING), ("date", ASCENDING)], unique=True)
    await db.skill_gap_analysis.create_index([("user_id", ASCENDING)])
    await db.skill_gap_analysis.create_index([("career_path_id", ASCENDING)])
    await db.skill_gap_analysis.create_index([("analysis_date", ASCENDING)])
    await db.skill_gap_analysis.create_index([("user_id", ASCENDING), ("career_path_id", ASCENDING)])
    await db.career_readiness_scores.create_index([("user_id", ASCENDING)])
    await db.career_readiness_scores.create_index([("career_path_id", ASCENDING)])
    await db.career_readiness_scores.create_index([("calculated_at", ASCENDING)])
    await db.career_readiness_scores.create_index([("user_id", ASCENDING), ("career_path_id", ASCENDING)])
    await db.projects.create_index([("slug", ASCENDING)], unique=True)
    await db.projects.create_index([("career_path_id", ASCENDING)])
    await db.projects.create_index([("related_careers", ASCENDING)])
    await db.projects.create_index([("difficulty", ASCENDING)])
    await db.projects.create_index([("is_active", ASCENDING)])
    await db.user_project_progress.create_index([("user_id", ASCENDING)])
    await db.user_project_progress.create_index([("project_id", ASCENDING)])
    await db.user_project_progress.create_index([("career_path_id", ASCENDING)])
    await db.user_project_progress.create_index([("status", ASCENDING)])
    await db.user_project_progress.create_index([("user_id", ASCENDING), ("project_id", ASCENDING)], unique=True)
    await db.portfolio_readiness.create_index([("user_id", ASCENDING)])
    await db.portfolio_readiness.create_index([("career_path_id", ASCENDING)])
    await db.portfolio_readiness.create_index([("calculated_at", ASCENDING)])
    await db.portfolio_readiness.create_index([("user_id", ASCENDING), ("career_path_id", ASCENDING)])
    await db.resumes.create_index([("user_id", ASCENDING)], unique=True)
    await db.resume_feedback.create_index([("user_id", ASCENDING)])
    await db.resume_feedback.create_index([("resume_id", ASCENDING)])
    await db.resume_feedback.create_index([("generated_at", ASCENDING)])
    await db.interview_questions.create_index([("career_path_id", ASCENDING)])
    await db.interview_questions.create_index([("type", ASCENDING)])
    await db.interview_questions.create_index([("difficulty", ASCENDING)])
    await db.user_interview_progress.create_index([("user_id", ASCENDING)])
    await db.user_interview_progress.create_index([("question_id", ASCENDING)])
    await db.user_interview_progress.create_index([("career_path_id", ASCENDING)])
    await db.user_interview_progress.create_index([("user_id", ASCENDING), ("question_id", ASCENDING)], unique=True)
    await db.certifications.create_index([("career_path_id", ASCENDING)])
    await db.certifications.create_index([("provider", ASCENDING)])
    await db.certifications.create_index([("difficulty", ASCENDING)])
    await db.certifications.create_index([("is_active", ASCENDING)])
    await db.user_certifications.create_index([("user_id", ASCENDING)])
    await db.user_certifications.create_index([("certification_id", ASCENDING)])
    await db.user_certifications.create_index([("career_path_id", ASCENDING)])
    await db.user_certifications.create_index([("user_id", ASCENDING), ("certification_id", ASCENDING)], unique=True)
