import asyncio
from typing import Any

from motor.motor_asyncio import AsyncIOMotorClient

from app.core.config import settings
from app.db.indexes import create_indexes
from app.models.career_model import create_career_document
from app.models.base_model import utc_now

CAREER_PATHS: list[dict[str, Any]] = [
    {
        "title": "AI Engineer",
        "slug": "ai-engineer",
        "description": "Designs intelligent systems that use machine learning, language models, and automation.",
        "overview": "AI Engineers turn data and algorithms into products that reason, predict, and automate decisions.",
        "difficulty_level": "advanced",
        "average_duration_months": 12,
        "required_skills": ["Python", "Machine Learning", "Data Analysis", "Mathematics", "Statistics"],
        "recommended_tools": ["Python", "PyTorch", "TensorFlow", "Jupyter", "FastAPI"],
        "responsibilities": ["Build AI prototypes", "Train and evaluate models", "Deploy intelligent APIs", "Monitor model quality"],
        "suggested_projects": ["AI chatbot", "Image classifier", "Recommendation prototype"],
        "recommended_certifications": ["Google Machine Learning Crash Course", "DeepLearning.AI Machine Learning Specialization"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["Artificial Intelligence", "Machine Learning", "Research and experimentation", "Python"],
        "related_subjects": ["Artificial Intelligence", "Mathematics", "Statistics", "Algorithms"],
        "preferred_personality_traits": ["Curious", "Analytical", "Patient"],
        "preferred_learning_styles": ["Project-based learning", "Reading documentation", "Mixed learning"],
        "icon": "hardware-chip",
        "color": "#7C3AED",
    },
    {
        "title": "Machine Learning Engineer",
        "slug": "machine-learning-engineer",
        "description": "Builds reliable machine learning pipelines, models, and production prediction services.",
        "overview": "Machine Learning Engineers bridge experimentation and production-grade model deployment.",
        "difficulty_level": "advanced",
        "average_duration_months": 12,
        "required_skills": ["Python", "Machine Learning", "Data Analysis", "SQL", "Statistics"],
        "recommended_tools": ["Python", "Scikit-learn", "MLflow", "Docker", "FastAPI"],
        "responsibilities": ["Prepare datasets", "Train models", "Deploy model services", "Improve model performance"],
        "suggested_projects": ["Customer churn predictor", "ML API service", "Model evaluation dashboard"],
        "recommended_certifications": ["AWS Machine Learning Specialty", "DeepLearning.AI MLOps Specialization"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["Machine Learning", "Data Science", "Research and experimentation", "Model deployment"],
        "related_subjects": ["Artificial Intelligence", "Statistics", "Mathematics", "Databases"],
        "preferred_personality_traits": ["Analytical", "Detail oriented", "Persistent"],
        "preferred_learning_styles": ["Project-based learning", "Practice exercises", "Mixed learning"],
        "icon": "analytics",
        "color": "#0891B2",
    },
    {
        "title": "Data Scientist",
        "slug": "data-scientist",
        "description": "Analyzes data to discover patterns, build insights, and support decisions.",
        "overview": "Data Scientists combine statistics, programming, and storytelling to solve business and research questions.",
        "difficulty_level": "intermediate",
        "average_duration_months": 9,
        "required_skills": ["Python", "SQL", "Statistics", "Data Analysis", "Machine Learning"],
        "recommended_tools": ["Python", "Pandas", "NumPy", "Power BI", "Jupyter"],
        "responsibilities": ["Clean datasets", "Analyze trends", "Build predictive models", "Present insights"],
        "suggested_projects": ["Sales analysis report", "Student performance dashboard", "Prediction notebook"],
        "recommended_certifications": ["IBM Data Science Professional Certificate", "Google Data Analytics Certificate"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["Data Science", "Analyzing data", "Statistics", "Analytics"],
        "related_subjects": ["Statistics", "Mathematics", "Databases", "Artificial Intelligence"],
        "preferred_personality_traits": ["Analytical", "Communicative", "Curious"],
        "preferred_learning_styles": ["Practice exercises", "Project-based learning", "Videos"],
        "icon": "bar-chart",
        "color": "#16A34A",
    },
    {
        "title": "Backend Developer",
        "slug": "backend-developer",
        "description": "Builds server-side APIs, databases, authentication, and business logic.",
        "overview": "Backend Developers create the reliable services that power web, mobile, and enterprise products.",
        "difficulty_level": "intermediate",
        "average_duration_months": 8,
        "required_skills": ["Python", "FastAPI", "SQL", "MongoDB", "Git/GitHub"],
        "recommended_tools": ["FastAPI", "PostgreSQL", "MongoDB", "Docker", "Postman"],
        "responsibilities": ["Build APIs", "Design databases", "Implement authentication", "Optimize performance"],
        "suggested_projects": ["JWT auth API", "Task management backend", "E-commerce API"],
        "recommended_certifications": ["Meta Back-End Developer", "MongoDB Developer Certification"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["Software Engineering", "Backend", "Building applications", "APIs"],
        "related_subjects": ["Programming", "Databases", "Data Structures", "Algorithms"],
        "preferred_personality_traits": ["Structured", "Problem solver", "Reliable"],
        "preferred_learning_styles": ["Project-based learning", "Reading documentation", "Practice exercises"],
        "icon": "server",
        "color": "#2563EB",
    },
    {
        "title": "Frontend Developer",
        "slug": "frontend-developer",
        "description": "Creates responsive, accessible, and polished user interfaces for web applications.",
        "overview": "Frontend Developers transform product ideas and designs into interactive browser experiences.",
        "difficulty_level": "beginner",
        "average_duration_months": 6,
        "required_skills": ["JavaScript", "TypeScript", "React", "HTML/CSS", "Git/GitHub"],
        "recommended_tools": ["React", "TypeScript", "Vite", "Figma", "Chrome DevTools"],
        "responsibilities": ["Build UI components", "Connect APIs", "Improve accessibility", "Optimize frontend performance"],
        "suggested_projects": ["Portfolio website", "Dashboard UI", "API-powered web app"],
        "recommended_certifications": ["Meta Front-End Developer", "freeCodeCamp Front End Libraries"],
        "market_demand": "high",
        "salary_level": "medium",
        "tags": ["Web Development", "Frontend", "Building applications", "Interfaces"],
        "related_subjects": ["Web Development", "Programming", "Human Computer Interaction", "Algorithms"],
        "preferred_personality_traits": ["Creative", "Detail oriented", "User focused"],
        "preferred_learning_styles": ["Project-based learning", "Videos", "Practice exercises"],
        "icon": "code-slash",
        "color": "#F97316",
    },
    {
        "title": "Mobile App Developer",
        "slug": "mobile-app-developer",
        "description": "Builds mobile applications for Android and iOS using native or cross-platform tools.",
        "overview": "Mobile App Developers create app experiences that work smoothly across devices and screen sizes.",
        "difficulty_level": "intermediate",
        "average_duration_months": 8,
        "required_skills": ["React Native", "JavaScript", "TypeScript", "Git/GitHub", "Mobile Development"],
        "recommended_tools": ["React Native", "Expo", "Android Studio", "Xcode", "Firebase"],
        "responsibilities": ["Build mobile screens", "Manage app navigation", "Integrate APIs", "Test on devices"],
        "suggested_projects": ["Habit tracker app", "Campus guide app", "Expense tracker app"],
        "recommended_certifications": ["Meta React Native Specialization", "Android Basics with Compose"],
        "market_demand": "medium",
        "salary_level": "medium",
        "tags": ["Mobile Development", "Building applications", "React Native", "Apps"],
        "related_subjects": ["Mobile Development", "Programming", "Human Computer Interaction", "Databases"],
        "preferred_personality_traits": ["Product minded", "Patient", "Practical"],
        "preferred_learning_styles": ["Project-based learning", "Videos", "Mixed learning"],
        "icon": "phone-portrait",
        "color": "#14B8A6",
    },
    {
        "title": "Cybersecurity Analyst",
        "slug": "cybersecurity-analyst",
        "description": "Protects systems by monitoring threats, analyzing vulnerabilities, and improving defenses.",
        "overview": "Cybersecurity Analysts combine networks, systems, and investigation skills to reduce security risk.",
        "difficulty_level": "intermediate",
        "average_duration_months": 9,
        "required_skills": ["Cybersecurity Basics", "Networks", "Python", "Git/GitHub", "SQL"],
        "recommended_tools": ["Wireshark", "Linux", "Nmap", "Burp Suite", "Splunk"],
        "responsibilities": ["Monitor alerts", "Investigate incidents", "Test vulnerabilities", "Document security controls"],
        "suggested_projects": ["Network scan lab", "Security checklist", "Log analysis project"],
        "recommended_certifications": ["CompTIA Security+", "Google Cybersecurity Certificate"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["Cybersecurity", "Security", "Solving security problems", "Networks"],
        "related_subjects": ["Security", "Networks", "Programming", "Databases"],
        "preferred_personality_traits": ["Careful", "Investigative", "Ethical"],
        "preferred_learning_styles": ["Practice exercises", "Reading documentation", "Mixed learning"],
        "icon": "shield-checkmark",
        "color": "#DC2626",
    },
    {
        "title": "Cloud Engineer",
        "slug": "cloud-engineer",
        "description": "Designs and manages cloud infrastructure, deployments, storage, and networking.",
        "overview": "Cloud Engineers help teams run secure, scalable services on cloud platforms.",
        "difficulty_level": "intermediate",
        "average_duration_months": 9,
        "required_skills": ["Cloud Basics", "Networks", "Git/GitHub", "Python", "SQL"],
        "recommended_tools": ["AWS", "Azure", "Docker", "Terraform", "Linux"],
        "responsibilities": ["Configure cloud services", "Manage deployments", "Improve reliability", "Secure infrastructure"],
        "suggested_projects": ["Deploy a backend API", "Static website on cloud storage", "Server monitoring dashboard"],
        "recommended_certifications": ["AWS Cloud Practitioner", "Azure Fundamentals"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["Cloud Computing", "Cloud", "Working with infrastructure", "Deployment"],
        "related_subjects": ["Networks", "Databases", "Programming", "Security"],
        "preferred_personality_traits": ["Organized", "Reliable", "Systems thinker"],
        "preferred_learning_styles": ["Project-based learning", "Reading documentation", "Practice exercises"],
        "icon": "cloud",
        "color": "#0284C7",
    },
    {
        "title": "DevOps Engineer",
        "slug": "devops-engineer",
        "description": "Automates software delivery, infrastructure, CI/CD pipelines, and operational workflows.",
        "overview": "DevOps Engineers connect development and operations so teams can ship reliably and quickly.",
        "difficulty_level": "advanced",
        "average_duration_months": 12,
        "required_skills": ["Git/GitHub", "Cloud Basics", "Python", "Networks", "SQL"],
        "recommended_tools": ["Docker", "GitHub Actions", "Kubernetes", "Terraform", "Linux"],
        "responsibilities": ["Build CI/CD pipelines", "Automate deployments", "Monitor systems", "Improve release reliability"],
        "suggested_projects": ["CI/CD pipeline", "Dockerized app deployment", "Infrastructure as code lab"],
        "recommended_certifications": ["AWS Developer Associate", "Docker Certified Associate"],
        "market_demand": "high",
        "salary_level": "high",
        "tags": ["DevOps", "Cloud Computing", "Working with infrastructure", "Automation"],
        "related_subjects": ["Networks", "Programming", "Security", "Databases"],
        "preferred_personality_traits": ["Automation minded", "Calm under pressure", "Systems thinker"],
        "preferred_learning_styles": ["Project-based learning", "Reading documentation", "Practice exercises"],
        "icon": "git-branch",
        "color": "#475569",
    },
    {
        "title": "UI/UX Designer",
        "slug": "ui-ux-designer",
        "description": "Designs user experiences, wireframes, prototypes, and usable digital interfaces.",
        "overview": "UI/UX Designers research users and design interfaces that are clear, accessible, and visually polished.",
        "difficulty_level": "beginner",
        "average_duration_months": 6,
        "required_skills": ["UI/UX Design", "HTML/CSS", "React", "Git/GitHub", "Human Computer Interaction"],
        "recommended_tools": ["Figma", "FigJam", "Miro", "Notion", "Chrome DevTools"],
        "responsibilities": ["Research users", "Create wireframes", "Build prototypes", "Validate interface decisions"],
        "suggested_projects": ["Mobile app prototype", "Design system sample", "Website usability redesign"],
        "recommended_certifications": ["Google UX Design Certificate", "Interaction Design Foundation Courses"],
        "market_demand": "medium",
        "salary_level": "medium",
        "tags": ["UI/UX Design", "Designing interfaces", "Human Computer Interaction", "Frontend"],
        "related_subjects": ["Human Computer Interaction", "Web Development", "Programming", "Mobile Development"],
        "preferred_personality_traits": ["Empathetic", "Creative", "Detail oriented"],
        "preferred_learning_styles": ["Project-based learning", "Videos", "Mixed learning"],
        "icon": "color-palette",
        "color": "#DB2777",
    },
]


async def seed_career_paths() -> None:
    client = AsyncIOMotorClient(settings.mongo_uri, uuidRepresentation="standard")
    db = client[settings.database_name]
    await create_indexes(db)
    try:
        for payload in CAREER_PATHS:
            existing = await db.career_paths.find_one({"slug": payload["slug"]})
            document = create_career_document(payload)
            if existing:
                document["created_at"] = existing.get("created_at", document["created_at"])
                document["updated_at"] = utc_now()
                await db.career_paths.update_one({"slug": payload["slug"]}, {"$set": document})
            else:
                await db.career_paths.insert_one(document)
        print(f"Seeded {len(CAREER_PATHS)} career paths.")
    finally:
        client.close()


if __name__ == "__main__":
    asyncio.run(seed_career_paths())
